### ISSUE TITLE
[QUESTION] When did you update to 1.21.1? I want this beautiful mod :D

### ISSUE THREAD

**Issue by Psychodeus** [Darkhax-Minecraft/Gilded-Sherds#3]
### Question

<title>

**Comment by Darkhax** [comment]
Hello, this update took longer than expected but you can now find it [here](https://www.curseforge.com/minecraft/mc-mods/gilded-sherds/files/all?page=1&pageSize=20&version=1.21.1). The newer Minecraft versions will be coming later.
